### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by kevin4dhd** [simplewidgets/countries_world_map#6]
It's been 3 months since the last update there are new countries,

**Comment by LauDijksterhuis** [comment]
Hello @kevin4dhd ,
Unfortunately there are no new countries yet.

At the moment I am working on a file generator that will create interactive maps for all countries via SVG input.
When this works there are two possible ways I will implement this:

1. Automaticcally creating separate packages for each country and publish them to pub.dev
2. Creating a new package which requires input files (SVG/JSON/DART) to work

The reason for this approach is to not bundle all countries in one package, because some developers will only need one country in the app.

**Comment by LauDijksterhuis** [comment]
I know it has been a while, but I am pleased to announce: with the last release version 1.0.0. There are over 130 countries available.

**Comment by LauDijksterhuis** [comment]
‼️ Please note

The latest release DOES have breaking changes! And will not work with the old map.
Please read the README.md to get started! Or ask me a question.
